// generated by ginger from go generate -- DO NOT EDIT
package main

import (
	"fmt"
	"github.com/davecgh/go-spew/spew"
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	"log"
	"net/http"
	"strconv"
	"time"
)

type SlackUserResource struct {
	db gorm.DB
}

// @Title CreateSlackUser
// @Description get string by ID
// @Accept  json
// @Param   some_id     path    int     true        "Some ID"
// @Success 201 {object} string
// @Failure 400 {object} APIError "problem decoding body"
// @Router /slackUser/ [post]
func (tr *SlackUserResource) CreateSlackUser(c *gin.Context) {
	var slackUser SlackUser

	if c.Bind(&slackUser) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	//slackUser.Status = SlackUserStatus
	slackUser.Ginger_Created = int32(time.Now().Unix())

	spew.Dump(slackUser.Profile)
	tr.db.Save(&slackUser)
	tr.db.Save(&(slackUser.Profile))

	c.JSON(http.StatusCreated, slackUser)
}

func (tr *SlackUserResource) GetAllSlackUsers(c *gin.Context) {
	var slackUsers []SlackUser

	tr.db.Order("ginger__created desc").Find(&slackUsers)

	c.JSON(http.StatusOK, slackUsers)
}

func (tr *SlackUserResource) GetSlackUser(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var slackUser SlackUser

	if tr.db.First(&slackUser, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Model(&slackUser).Related(&(slackUser.Profile), "ProfileId")
		c.JSON(http.StatusOK, slackUser)
	}
}

func (tr *SlackUserResource) UpdateSlackUser(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var slackUser SlackUser

	if c.Bind(&slackUser) != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding body"})
		return
	}
	slackUser.Ginger_Id = int32(id)

	var existing SlackUser

	if tr.db.First(&existing, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Save(&slackUser)
		c.JSON(http.StatusOK, slackUser)
	}

}

func (tr *SlackUserResource) PatchSlackUser(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	// this is a hack because Gin falsely claims my unmarshalled obj is invalid.
	// recovering from the panic and using my object that already has the json body bound to it.
	var json []Patch

	r := c.Bind(&json)
	if r != nil {
		fmt.Println(r)
	} else {
		if json[0].Op != "replace" && json[0].Path != "/status" {
			c.JSON(http.StatusBadRequest, gin.H{"message": "PATCH support is limited and can only replace the /status path"})
			return
		}
		var slackUser SlackUser

		if tr.db.First(&slackUser, id).RecordNotFound() {
			c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
		} else {
			//slackUser.Status = json[0].Value

			tr.db.Save(&slackUser)
			c.JSON(http.StatusOK, slackUser)
		}
	}
}

func (tr *SlackUserResource) DeleteSlackUser(c *gin.Context) {
	id, err := tr.getId(c)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "problem decoding id sent"})
		return
	}

	var slackUser SlackUser

	if tr.db.First(&slackUser, id).RecordNotFound() {
		c.JSON(http.StatusNotFound, gin.H{"message": "not found"})
	} else {
		tr.db.Delete(&slackUser)
		c.Data(http.StatusNoContent, "application/json", make([]byte, 0))
	}
}

func (tr *SlackUserResource) getId(c *gin.Context) (int32, error) {
	idStr := c.Params.ByName("id")
	id, err := strconv.Atoi(idStr)
	if err != nil {
		log.Print(err)
		return 0, err
	}
	return int32(id), nil
}

/**
* on patching: http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/
 *
  * patch specification https://tools.ietf.org/html/rfc5789
   * json definition http://tools.ietf.org/html/rfc6902
*/

type Patch struct {
	Op    string `json:"op" binding:"required"`
	From  string `json:"from"`
	Path  string `json:"path"`
	Value string `json:"value"`
}
