// generated by ginger from go generate -- DO NOT EDIT

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type Config struct {
	SvcHost    string
	DbUser     string
	DbPassword string
	DbHost     string
	DbName     string
	Token      string
	Url        string
}

type SlackUserService struct {
}

func (s *SlackUserService) getDb(cfg Config) (gorm.DB, error) {
	db, err := gorm.Open("sqlite3", "/tmp/"+cfg.DbName)
	db.LogMode(true)
	return db, err
}

func (s *SlackUserService) Migrate(cfg Config) error {
	db, err := s.getDb(cfg)
	if err != nil {
		return err
	}
	db.SingularTable(true)

	db.AutoMigrate(&SlackUser{})
	db.AutoMigrate(&ProfileType{})
	return nil
}
func (s *SlackUserService) Run(cfg Config) error {
	db, err := s.getDb(cfg)
	if err != nil {
		return err
	}
	db.SingularTable(true)

	slackUserResource := &SlackUserResource{db: db}

	r := gin.Default()
	//gin.SetMode(gin.ReleaseMode)

	r.GET("/slackUser", slackUserResource.GetAllSlackUsers)
	r.GET("/slackUser/:id", slackUserResource.GetSlackUser)
	r.POST("/slackUser", slackUserResource.CreateSlackUser)
	r.PUT("/slackUser/:id", slackUserResource.UpdateSlackUser)
	r.PATCH("/slackUser/:id", slackUserResource.PatchSlackUser)
	r.DELETE("/slackUser/:id", slackUserResource.DeleteSlackUser)

	r.Run(cfg.SvcHost)

	return nil
}
